_$header
#include "header.inc"

_$logical(doCap,null)
_$logical(doNI,null)
_$logical(doThruUC,null)
_$double(sinNoKids,amount)
_$double(sinKids,amount)
_$double(couNoKids,amount)
_$double(couKids,amount)
_$logical(higherInLondon,null)
_$double(LondonSinNoKids,amount)
_$double(LondonSinKids,amount)
_$double(LondonCouNoKids,amount)
_$double(LondonCouKids,amount)
_$double(UCEarnThr,amount)

_$footer
