_$header
#include "header.inc"

_$logical(doUnivCred,null)
_$double(MainCou,amount)     
_$double(YngCou,amount)      
_$double(MainSin,amount)     
_$double(YngSin,amount)    
_$integer(MinAgeMain,range)
_$double(FirstKid,amount)
_$double(OtherKid,amount)
_$double(MaxCC1,amount)     
_$double(MaxCC2,amount)         
_$double(PropCC,rate)       
_$integer(MaxAgeCC,range)
_$logical(doRentCap,null)
_$double(DisregSinNoKidsHi,amount)
_$double(DisregSinNoKidsLo,amount)
_$double(DisregSinKidsHi,amount)
_$double(DisregSinKidsLo,amount)
_$double(DisregCouNoKidsHi,amount)
_$double(DisregCouNoKidsLo,amount)
_$double(DisregCouKidsHi,amount)
_$double(DisregCouKidsLo,amount)
_$double(taper,rate)
_$double(MinAmt,minamount)

_$footer
