_$header
_$lab(1,north_east,'North East')
_$lab(2,north_west,'North West and Merseyside')
_$lab(3,yorks,'Yorks and Humberside')
_$lab(4,east_midlands,'East Midlands')
_$lab(5,west_midlands,'West Midlands')
_$lab(6,eastern,'Eastern')
_$lab(7,london,'London')
_$lab(8,south_east,'South East')
_$lab(9,south_west,'South West')
_$lab(10,wales,'Wales')
_$lab(11,scotland,'Scotland')
_$labn(12,northern_ireland,'Northern Ireland')
_$footer