@:defconst(maxKids, 16)            #! maximum number of children for fam_t
@:defconst(maxRPI, 1024)           #! maximum price indices
@:defconst(MaxNumAgeRng, 32)       #! maximum age ranges in parts of sys_t
@:defconst(MaxIncTaxBands, 32)     #! maximum income tax bands
@:defconst(MaxNatInsC4Bands, 32)   #! maximum natins bands
@:defconst(MaxNatInsC4Bands, 32)   #! maximum natins bands (class 4)
